---
title: "Linked registry sources"
---

`{phenotools}` currently supports linkage to NPR and the primary care registry KUHR. Details are provided in the package vignette. If your project involves linkage to other registry sources, it is recommended that you first curate a dataset using phenotools, and then follow the instructions below to find and manually incorporate other sources of phenotypic data.

-   For registry sources not currently handled by `{phenotools}`, you can look for the relevant files in `data/durable/data`. You should be able to identify which files you need using the directory structure.

In addition to the raw registry files, you will also need a linkage file to join registry information with MoBa IDs:

-   Each registry source has a bespoke linkage file, available in `data/durable/Linkage files`. The relevant IDs are, for individual children, *PREG_ID_2306* (or simply *preg_id* in `{phenotools}`-curated datasets) which uniquely identifies pregnancies, and *BARN_NR*, which distinguishes between twins with the same *preg_id*. For mothers, *M_ID_2306* (or *m_id* in `{phenotools}`) and *F_ID_2306* (*f_id*) are used.

Please be aware that incorrectly specified merges of large datasets can use enormous amounts of RAM - it is recommended that you test your code first on abbreviated versions of the datasets you intend to merge.
