---
title: "Navigating through TSD"
---

You can log into our TSD project via one of several "virtual machines" (VMs) that are avaiable. Most run Windows (win-01, win-02) etc, but there is also one RedHat Linux VM. Most of the instructions in this wiki relate to the Windows VMs, because we assume that if you are working in Linux you can probably figure everything out anyway. All VMs also allow you, once inside TSD, to connect to and use the high performance computing cluster, which is called ‘Colossus’.

Once you log onto your TSD windows machine you can set up your project’s data folders in in windows using the following steps:

1.  First read the documentation available [here](https://www.uio.no/english/services/it/research/sensitive-data/use-tsd/directories-files/shortcuts/index.html)

2.  [Map the project home directories to a drive](https://www.uio.no/english/services/it/research/sensitive-data/help/windows-shortcuts.html): //ess01/p471/data or //ess01/p471/cluster

## ***Project home directories: /data/durable (Windows) and /cluster (Colossus)***

Because analyses are conducted both on and off Colossus, there are two main ‘home’ directories associated with the project that you will use. The main home directory for our project on the Windows side (you mapped the drive for this above) is located at: **\>drive letter you chose during mapping\</data/durable.**

The main home directory for our project when working on Colossus is accessible via Putty, by typing `cd //ess/p471/cluster/`. This directory is *also* accessible via Windows, via \>drive letter you chose during mapping\</cluster, *but* the reverse is not true (i.e., the Windows-side storage data/durable is not directly accessible from the cluster).

These directories are separate, but have been set up with a similar structure, organised into the following sub-directories:

-   data (read-only location of datafiles; more details below)

-   projects (location of directories for specific analytic projects)

-   people (personal folders – please create one with your name here in both locations)

-   common (useful files for common use)

-   scratch (temporary storage of random files, files that do not fit elsewhere)

See the [Working with Colossus](https://osf.io/necbg/wiki/Working%20with%20Colossus%20%28the%20TSD%20HPCC%29/) section for details of how to transfer files between directories (most simply, this can now be done by using Windows File Explorer using the **//ess01/p471/cluster** mapping of the Colossus p471 home area).

## ***Locations of phenotypic and genetic data***

See the wiki sections on Using MoBa phenotype data and Using MoBa genetic data respectively.
