# Getting started with data in p471

## Using MoBa phenotype and linked registry data

Most users will need to access MoBa questionnaire data for their analyses. If your accepted analysis plan also specified use of linked registry data - for example from the Norwegian Patient Registry (NPR) or Statistics Norway (SSB) then you should also have access to those files. The next sections details best practices for interacting with these data sources.

::: callout-note
**IMPORTANT NOTICE**

We periodically receive updates from MoBa that reflect participant withdrawals from the cohort. On receipt of a new "`SV_INFO`" file, we will notify all users via Teams and remove all withdrawn individuals from the central raw data files. **It is then all users' responsibility** to ensure that scripts are re-run and all interim data files in their analytic projects are recreated accordingly. Analyses that have been submitted, or are for publication do not need to be updated in this way.
:::

### Phenotools R package

The PaGe/PsychGen group has been developing an R package called [**phenotools**](https://github.com/psychgen/phenotools) that can be used to work with phenotype data from MoBa and linked registries (such as the Norwegian Patient Registry). It is still in development, and so comes with a warning (variables are still being quality controlled and up until v1 of the package you may need to re-run analyses if coding errors are discovered), but is currently our recommended way to curating datasets for your analyses.

On Windows you can install as follows (first check the common/software folder to see what the latest version is, replacing *x/y/z* below accordingly):

``` r
   install.packages("//tsd-evs/p471/data/durable/common/software/phenotools_x.y.z.zip", 
                     repos=NULL,
                     type = "binary")
```

...and then run `vignette('phenotools')` for examples and instructions. External to TSD, the code for `{phenotools}` will be periodically updated on [**Github**](https://github.com/psychgen/phenotools)**.**

Refer to the results of `available_variables(source="moba")` or to `phenotools::moba` / `phenotools::moba_varnames`, or directly to the MoBa annotated questionnaires and instrument synthesis documentation for what you can pull from the questionnaires data files.

Datasets curated using `{phenotools}` will automatically exclude withdrawn participants as described above.

### Linked registry sources

`{phenotools}` currently supports linkage to NPR and the primary care registry KUHR. Details are provided in the package vignette. If your project involves linkage to other registry sources, it is recommended that you first curate a dataset using phenotools, and then follow the instructions below to find and manually incorporate other sources of phenotypic data.

-   For registry sources not currently handled by `{phenotools}`, you can look for the relevant files in `data/durable/data`. You should be able to identify which files you need using the directory structure.

In addition to the raw registry files, you will also need a linkage file to join registry information with MoBa IDs:

-   Each registry source has a bespoke linkage file, available in `data/durable/Linkage files`. The relevant IDs are, for individual children, *PREG_ID_2306* (or simply *preg_id* in `{phenotools}`-curated datasets) which uniquely identifies pregnancies, and *BARN_NR*, which distinguishes between twins with the same *preg_id*. For mothers, *M_ID_2306* (or *m_id* in `{phenotools}`) and *F_ID_2306* (*f_id*) are used.

Please be aware that incorrectly specified merges of large datasets can use enormous amounts of RAM - it is recommended that you test your code first on abbreviated versions of the datasets you intend to merge.

### Best practices when not using Phenotools

If you prefer **not** to use the `{phenotools}` package, we recommend that you follow some of its guiding principles to ensure that your analyses are documented, reproducible, and minimize the local reproduction and storage of data. Code for analytic projects using phenotypic data in TSD p471 should:

-   Always refer back to raw files centrally located in data/durable/data

-   Be complete enough to allow analyses to be re-run from full starting only with the code and the raw data files

-   Minimize the creation of interim data files with participant identifying information. When necessary, such files should be created programmatically on the basis of raw files, should be stored in a specific directory within the project folder, and should be prioritized for deletion when analyses are complete

-   Be well-documented and suitable for export with results at the end of the project (data preparation code *must* be submitted to MoBa prior to submission - see [MoBa publication guidelines](https://www.fhi.no/en/studies/moba/for-forskere-artikler/checklist-for-papers/) - and all analytic code should ideally be published alongside empirical papers)

## Using MoBa genetic data in p471

The genetic data available for use in p471 has been quality-controlled using the [MoBaPsychGen v.1 QC pipeline](https://www.biorxiv.org/content/10.1101/2022.06.23.496289v1). All details are available in the preprint (linked above) and code for the pipeline is available on the associated [github repository](https://github.com/psychgen/MoBaPsychGen-QC-pipeline). **Please try to find answers to questions you may have about the QC in these sources before contacting the QC team**.

### MoBaPsychGen v.1 genetic data files

You can find the genetic data, and accompanying files relevant for analyses in the `data/durable` area of the shared drive, under `/data/genetic_data/MoBaPsychGen_v1`.

The README files in these folders detail what each file is, how it should be used, and several important points to consider *before* using the the genetic data. **Please read the contents of this file**.

The requirement to periodically delete individuals withdrawing consent for participation in MoBa (detailed in full [here](https://osf.io/necbg/wiki/Using%20MoBa%20phenotype%20data/)) applies equally to genetic data. The genetic data files in these managed locations will be updated centrally when we receive updated consent information. Please look out for notifications on the Teams space, as once these updates are made it becomes your responsibility to re-run analyses with the updated sample if work on your project is still ongoing.

### Using the Genotools R package to work with genetic data

The PaGe/PsychGen group has been developing an R package called [**genotools**](https://github.com/psychgen/genotools) (sister to the **phenotools** package described in the section on using phenotypic data) that can be used to work with genetic data diles from the MobaPsychGen QC pipeline. It is still in development, and so comes with relatively limited functionality and a health warning, but is currently a useful way to create (and use pre-created polygenic scores), merge genetic and phenotypic data, and filter an analytic sample for different degrees of relatedness.

On Windows you can install as follows (first check the common/software folder to see what the latest version is, replacing *x/y/z* below accordingly):

``` r
  install.packages("//tsd-evs/p471/data/durable/common/software/genotools_x.y.z.zip", 
                     repos=NULL,
                     type = "binary")
```

...and then run `vignette('genotools')` for examples and instructions. External to TSD, the code for `{genotools}` will be periodically updated on [Github](https://github.com/psychgen/genotools).
