---
title: "Export"
---

In this section you can find information about how to export files to/from TSD. To export results from TSD please use the template included below.

------------------------------------------------------------------------

## Exporting results from TSD

#### What is personal data?

Personal data is all information on the individual level. This is either results from completed analysis or raw data containing information on the individual. All group data with fewer than ten (\<10) individuals are considered personal data. Even personal data that is anonymised is considered personal data (this includes genetic data).

**Rule of thumb:** any line of data that is related to an individual is considered personal data.

#### Where to put the files you want to export on TSD

1.  Put the file(s) you need to export in `data/durable/common/Exported` files, within a folder with your name. NB: It is recommended that you copy files in individually rather than entire folders, to minimise the risk of accidentally including data files, such as .RData disk image snapshots, which may be hidden by default (we recommend that you make these visible to ticking the relevant box under the "View" tab in Windows Explorer).

2.  Write the date at the start of the filename or folder (if multiple files).

3.  Ensure that there are no individual-level data or results on groups of fewer than 10 (\<10) individuals in your file(s).

### Export requests e-mail template

1.  [Please use this pre-filled e-mail template](mailto:stianbarbo.valand@fhi.no;Laura.Elizabeth.Hegemann\@fhi.no;helga.ask@fhi.no;Laurie.Hannigan@fhi.no;Alexandra.Havdahl@fhi.no?body=TSD%20path:) when requesting files.

<!-- -->

2.  Please copy the table below into your request e-mail:

| Filename (similar files may be grouped for convenience) | Contents | Reason | I confirm that there is no personal data in the exported file request |
|------------------|------------------|------------------|------------------|
| Example.txt | Summary of results for... | Inclusion in manuscript | Confirmed |
| Figure 1.pdf | Network plots | Inclusion in Supplementary Materials | Confirmed |
|  |  |  |  |

3.  Attach your approved analytical plan

::: {.callout-note appearance="minimal" icon="false"}
## Pre-filled e-mail not working?

Send export request e-mail to the following: **StianBarbo.Valand\@fhi.no; Alexandra.Havdahl\@fhi.no; Helga.Ask\@fhi.no; Laura.Elizabeth.Hegemann\@fhi.no>**

Please note that exporting is a time-consuming and high stakes endeavour for us that must be carried out alongside our other work. Our aim is to action all export requests within one week during non-holiday periods. Please be patient and plan your exports with this time lag in mind as far as possible. 

-TSD path:

-Copy the table in point 2
:::
