---
title: "Using MoBa genetic data in p471"
---

The genetic data available for use in p471 has been quality-controlled using the [MoBaPsychGen v.1 QC pipeline](https://www.biorxiv.org/content/10.1101/2022.06.23.496289v1). All details are available in the preprint (linked above) and code for the pipeline is available on the associated [github repository](https://github.com/psychgen/MoBaPsychGen-QC-pipeline). **Please try to find answers to questions you may have about the QC in these sources before contacting the QC team**.

### MoBaPsychGen v.1 genetic data files

You can find the genetic data, and accompanying files relevant for analyses in the `data/durable` area of the shared drive, under `/data/genetic_data/MoBaPsychGen_v1`.

The README files in these folders detail what each file is, how it should be used, and several important points to consider *before* using the the genetic data. **Please read the contents of this file**.

The requirement to periodically delete individuals withdrawing consent for participation in MoBa (detailed in full [here](https://osf.io/necbg/wiki/Using%20MoBa%20phenotype%20data/)) applies equally to genetic data. The genetic data files in these managed locations will be updated centrally when we receive updated consent information. Please look out for notifications on the Teams space, as once these updates are made it becomes your responsibility to re-run analyses with the updated sample if work on your project is still ongoing.

### Using {genotools} R package to work with genetic data

The PaGe/PsychGen group has been developing an R package called [**genotools**](https://github.com/psychgen/genotools) (sister to the **phenotools** package described in the section on using phenotypic data) that can be used to work with genetic data diles from the MobaPsychGen QC pipeline. It is still in development, and so comes with relatively limited functionality and a health warning, but is currently a useful way to create (and use pre-created polygenic scores), merge genetic and phenotypic data, and filter an analytic sample for different degrees of relatedness.

On Windows you can install as follows (first check the common/software folder to see what the latest version is, replacing *x/y/z* below accordingly):

``` r
  install.packages("//tsd-evs/p471/data/durable/common/software/genotools_x.y.z.zip", 
                     repos=NULL,
                     type = "binary")
```

...and then run `vignette('genotools')` for examples and instructions. External to TSD, the code for `{genotools}` will be periodically updated on [Github](https://github.com/psychgen/genotools).


