---
title: "Using the {genotools} R package to work with genetic data"
---

The PaGe/PsychGen group has been developing an R package called [**genotools**](https://github.com/psychgen/genotools) (sister to the **phenotools** package described in the section on using phenotypic data) that can be used to work with genetic data diles from the MobaPsychGen QC pipeline. It is still in development, and so comes with relatively limited functionality and a health warning, but is currently a useful way to create (and use pre-created polygenic scores), merge genetic and phenotypic data, and filter an analytic sample for different degrees of relatedness.

On Windows you can install as follows (first check the common/software folder to see what the latest version is, replacing *x/y/z* below accordingly):

``` R
  install.packages("//tsd-evs/p471/data/durable/common/software/genotools_x.y.z.zip", 
                     repos=NULL,
                     type = "binary")
```

...and then run `vignette('genotools')` for examples and instructions. External to TSD, the code for `{genotools}` will be periodically updated on [Github](https://github.com/psychgen/genotools).
