---
title: "Using MoBa phenotype and linked registry data"
---

Most users will need to access MoBa questionnaire data for their analyses. If your accepted analysis plan also specified use of linked registry data - for example from the Norwegian Patient Registry (NPR) or Statistics Norway (SSB) then you should also have access to those files. The next sections details best practices for interacting with these data sources.

::: callout-important
## IMPORTANT NOTICE

We periodically receive updates from MoBa that reflect participant withdrawals from the cohort. On receipt of a new "`SV_INFO`" file, we will notify all users via [Teams](https://osf.io/necbg/wiki/Using%20MoBa%20phenotype%20data/) and remove all withdrawn individuals from the central raw data files. **It is then all users' responsibility** to ensure that scripts are re-run and all interim data files in their analytic projects are recreated accordingly. Analyses that have been submitted for publication do not need to be updated in this way.
:::
