---
title: "Troubleshooting: where to go for help"
---

For problems with first-time access to TSD, contact [StianBarbo.Valand\@fhi.no](mailto:StianBarbo.Valand@fhi.no).

For problems with access to TSD when you have previously connected successfully, or issues with Colossus, check the [TSD operational log](https://www.uio.no/english/services/it/research/sensitive-data/log/), post on the relevant Teams channel to see if the problem is user-specific or group-wide, or contact [tsd-drift\@usit.uio.no](mailto:tsd-drift@usit.uio.no).

For problems with phenotools, genotools, git/Gitea, project set-up, finding relevant files in TSD, or technical questions about using Colossus contact [laurie.hannigan\@bristol.ac.uk](mailto:laurie.hannigan@bristol.ac.uk) or post on the Teams channel.

For problems or questions regarding use of the MoBaPsychGen_v1 genetics data, check the [preprint](https://www.biorxiv.org/content/10.1101/2022.06.23.496289v2), post on the Teams channel, or *if absolutely necessary* contact [Elizabeth.Corfield\@fhi.no](mailto:Elizabeth.Corfield@fhi.no).

# FAQ

1.  Question?

Answer
