---
title: "High performance computing (HPC) - Colossus"
---

High performance computing (HPC) services are available via [Colossus](https://www.uio.no/english/services/it/research/sensitive-data/help/hpc/colossus-userguide.html). The information below is intended as a supplement to the Colossus user guide provided by UiO, covering specific issues related to the use of Colossus for PsychGen-related projects.

If you are an external collaborator, your PsychGen contact person must be made aware if you require use of HPC resources for your work in the project project.

The standard software for analysis in MoBa are **R and Stata**. If a program you require is not listed in the available applications, it is worth contacting your MoBa collaborator to see whether it can be installed.

For those of you more familiar with SPSS, SPSS data files are available and can be opened through R without needing SPSS (recommend using the `read_spss()` function from the `{haven}` package). SPSS only works for University of Oslo employees who get it for free, others need a license to use it in TSD. The MoBa phenotype data folder also contains Stata files.
