---
title: "Getting started with Services for Sensitive Data (TSD)"
date: "08/10/2024"
---

In order to access and analyse MoBa data you must become familiar with the Services for Sensitive Data (TSD) platform. A guide to the TSD is available [here](https://www.uio.no/english/services/it/research/sensitive-data/help/). TSD is a secure network that allows for UiO researchers and other collaborating institutions to share access to large amounts of sensitive data. If you have not already received TSD access contact your designated PsychGen contact person or the project coordination team.

Once you have set up access to TSD, you can log into our TSD project ("p471") via one of several "virtual machines" (VMs). Most run Windows (win-01, win-02) etc, but there is also one RedHat Linux VM. Most of the instructions in this wiki relate to the Windows VMs, because we assume that if you are working in Linux you can probably figure everything out anyway. 

All VMs also allow you, once inside TSD, to connect to and use the high performance computing cluster, which is called ‘Colossus’. Details for using Colossus can be found [here](tsd_3).

Next: [Navigating through TSD](tsd_2).


